name: boinor website CI

on:
  push:
    branches: 
      - sources

  pull_request:
    branches: 
      - sources

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.in
      - name: Build the website
        run: |
            make html
      - name: Deployment to Github Pages
        if: success() && github.ref == 'refs/heads/sources'
        run: |
            make publish-to-github-force
